---
title: "p8105_hw5_rk3445"
author: "Rosie Kwon"
date: "2025-11-01"
output: html_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

A function that checks whether there are duplicate birthdays in the group
```{r}
duplicate_birthday <- function(n, num_days = 365) {
  birthdays <- sample(0:(num_days - 1), n, replace = TRUE)
  if (length(birthdays) != length(unique(birthdays))) {
    return(TRUE)   
  } else {
    return(FALSE)  
  }
}
```

run this function 10000 times for each group size between 2 and 50. 
```{r}
output = vector("list", length = 50)

for(i in 2:50){
  output[[i]] =
    rerun(10000, duplicate_birthday(i, num_days = 365)) |> 
    unlist()
}

#For each group size, compute the probability that at least two people in the group will share a birthday by averaging across the 10000 simulation runs.
sim_results =
  tibble(
    group_size = 2:50,
    prob_shared = map_dbl(output[2:50], mean)
)

```

A plot showing the probability as a function of group size
```{r}
sim_results |>
  ggplot(aes(x = group_size, y = prob_shared)) +
  geom_point(size = 1, alpha = 0.3) + 
  geom_line(color = "darkorange", size = 1, alpha = 0.5) + 
  scale_y_continuous(labels = scales::percent_format()) + 
  labs(
    title = "Birthday Problem Simulation",
    x = "Group Size",
    y = "Probability of Shared Birthday"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold")
  )
  
```



